"""Standalone Live Jira HTTP/SSE Model Context Protocol (MCP) Server for Gemini Enterprise Agent Platform."""
import os
import logging
import httpx
from typing import Optional
from mcp.server.fastmcp import FastMCP

logger = logging.getLogger("jira-mcp-server")
logging.basicConfig(level=logging.INFO)

# Initialize FastMCP Server on port (supports Cloud Run PORT env var)
port = int(os.getenv("PORT", 8080))
mcp = FastMCP("Jira-Enterprise-MCP-Server", host="0.0.0.0", port=port)



def get_jira_auth_headers():
    domain = os.getenv("JIRA_DOMAIN", "upasanapati-1771922768188.atlassian.net")
    jira_email = os.getenv("JIRA_USER_EMAIL", "")
    jira_token = os.getenv("JIRA_API_TOKEN", "")
    return domain, (jira_email, jira_token)


@mcp.tool(
    name="jira_execute_jql",
    description="Execute raw Jira Query Language (JQL) queries directly against Jira (e.g. `project = WAR AND text ~ 'API latency'`). Gemini will construct JQL queries dynamically based on user requests."
)
def jira_execute_jql(jql: str) -> str:
    """Execute raw JQL query directly against Jira."""
    domain, auth = get_jira_auth_headers()
    clean_jql = jql.strip()
    url = f"https://{domain}/rest/api/3/search/jql"
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(
                url,
                auth=auth,
                headers={"Accept": "application/json"},
                params={"jql": clean_jql, "fields": "summary,status,assignee,key,description"}
            )
            if resp.status_code == 200:
                data = resp.json()
                issues = []
                for i in data.get("issues", []):
                    key = i.get("key")
                    summary = i.get("fields", {}).get("summary")
                    st = i.get("fields", {}).get("status", {}).get("name")
                    assignee = i.get("fields", {}).get("assignee", {}).get("displayName", "Unassigned") if i.get("fields", {}).get("assignee") else "Unassigned"
                    issues.append(f"- **{key}**: {summary} | Status: `{st}` | Assignee: {assignee}")
                
                count = len(issues)
                if count > 0:
                    return f"Found {count} issue(s) executing JQL `{clean_jql}`:\n" + "\n".join(issues)
                return f"Jira JQL Query `{clean_jql}` executed live against tenant `{domain}`. 0 issues found."
            return f"Jira API Error (HTTP {resp.status_code}): {resp.text}"
    except Exception as e:
        return f"Error executing JQL query: {str(e)}"


@mcp.tool(
    name="jira_search_issues",
    description="Execute custom Jira Query Language (JQL) searches or search Jira issues by project key, keyword query (e.g. 'API latency'), and status. Gemini can generate and pass raw JQL strings directly in the 'jql' parameter."
)
def jira_search_issues(jql: Optional[str] = None, project_key: str = "WAR", query: Optional[str] = None, status: Optional[str] = None) -> str:
    """Search Jira issues using custom JQL generated by Gemini or by keyword and status parameters."""
    domain, auth = get_jira_auth_headers()
    
    if jql and jql.strip():
        final_jql = jql.strip()
    else:
        clean_project = project_key.strip().upper()
        jql_parts = [f"project = '{clean_project}'"]
        if query and query.strip():
            clean_query = query.strip().replace("'", "\\'")
            jql_parts.append(f"text ~ '{clean_query}'")
        if status and status.strip():
            jql_parts.append(f"status = '{status.strip()}'")
        final_jql = " AND ".join(jql_parts)
        
    url = f"https://{domain}/rest/api/3/search/jql"
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(
                url,
                auth=auth,
                headers={"Accept": "application/json"},
                params={"jql": final_jql, "fields": "summary,status,assignee,key,description"}
            )
            if resp.status_code == 200:
                data = resp.json()
                issues = []
                for i in data.get("issues", []):
                    key = i.get("key")
                    summary = i.get("fields", {}).get("summary")
                    st = i.get("fields", {}).get("status", {}).get("name")
                    assignee = i.get("fields", {}).get("assignee", {}).get("displayName", "Unassigned") if i.get("fields", {}).get("assignee") else "Unassigned"
                    issues.append(f"- **{key}**: {summary} | Status: `{st}` | Assignee: {assignee}")
                
                count = len(issues)
                if count > 0:
                    return f"Found {count} issue(s) matching JQL `{final_jql}`:\n" + "\n".join(issues)
                return f"Jira JQL Query `{final_jql}` executed live against tenant `{domain}`. 0 issues found."
            return f"Jira API Error (HTTP {resp.status_code}): {resp.text}"
    except Exception as e:
        return f"Error executing Jira JQL search: {str(e)}"


def extract_adf_text(doc):
    if not doc:
        return ""
    if isinstance(doc, str):
        return doc
    if isinstance(doc, dict):
        if doc.get("type") == "text":
            return doc.get("text", "")
        if "content" in doc and isinstance(doc["content"], list):
            return "\n".join(filter(None, [extract_adf_text(c) for c in doc["content"]]))
    return ""


@mcp.tool(
    name="jira_get_issue",
    description="Retrieve specific Jira issue details by issue key (e.g. WAR-1, WAR-14)."
)
def jira_get_issue(issue_key: str) -> str:
    """Retrieve specific Jira issue details by issue key."""
    clean_key = issue_key.strip().upper()
    domain, auth = get_jira_auth_headers()
    url = f"https://{domain}/rest/api/3/issue/{clean_key}"
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(url, auth=auth, headers={"Accept": "application/json"})
            if resp.status_code == 200:
                data = resp.json()
                fields = data.get("fields", {})
                
                desc = fields.get("description")
                desc_text = extract_adf_text(desc) if desc else "No description provided."
                
                comments_list = fields.get("comment", {}).get("comments", [])
                formatted_comments = []
                for c in comments_list:
                    author = c.get("author", {}).get("displayName", "Unknown") if c.get("author") else "Unknown"
                    body_text = extract_adf_text(c.get("body"))
                    formatted_comments.append(f"  - [{author}]: {body_text}")
                
                comments_str = "\n".join(formatted_comments) if formatted_comments else "No comments on this issue."
                
                return (
                    f"Details for Jira Issue **{clean_key}**:\n"
                    f"- **Summary**: {fields.get('summary')}\n"
                    f"- **Status**: {fields.get('status', {}).get('name')}\n"
                    f"- **Assignee**: {fields.get('assignee', {}).get('displayName', 'Unassigned') if fields.get('assignee') else 'Unassigned'}\n"
                    f"- **Tenant**: {domain}\n"
                    f"- **Description**: {desc_text}\n"
                    f"- **Comments**:\n{comments_str}"
                )
            elif resp.status_code == 404:
                return f"Issue '{clean_key}' was not found on Jira tenant '{domain}'."
            return f"Jira API Error (HTTP {resp.status_code}): {resp.text}"
    except Exception as e:
        return f"Error fetching Jira issue: {str(e)}"


@mcp.tool(
    name="jira_create_issue",
    description="Create a new Jira issue/ticket in a specified project (e.g. WAR)."
)
def jira_create_issue(project_key: str, summary: str, description: str = "", issue_type: str = "Task") -> str:
    """Create a new Jira issue."""
    clean_project = project_key.strip().upper()
    domain, auth = get_jira_auth_headers()
    url = f"https://{domain}/rest/api/3/issue"
    payload = {
        "fields": {
            "project": {"key": clean_project},
            "summary": summary,
            "issuetype": {"name": issue_type},
            "description": {
                "type": "doc",
                "version": 1,
                "content": [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": description or summary}]
                    }
                ]
            }
        }
    }
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.post(url, auth=auth, headers={"Accept": "application/json", "Content-Type": "application/json"}, json=payload)
            if resp.status_code in [200, 201]:
                data = resp.json()
                key = data.get("key")
                return f"Successfully created Jira issue **{key}** in project **{clean_project}**! Issue URL: https://{domain}/browse/{key}"
            return f"Error creating Jira issue (HTTP {resp.status_code}): {resp.text}"
    except Exception as e:
        return f"Error creating Jira issue: {str(e)}"


@mcp.tool(
    name="jira_add_comment",
    description="Add a new comment to an existing Jira ticket (e.g. WAR-12)."
)
def jira_add_comment(issue_key: str, comment_text: str) -> str:
    """Add a new comment to a Jira ticket."""
    clean_key = issue_key.strip().upper()
    domain, auth = get_jira_auth_headers()
    url = f"https://{domain}/rest/api/3/issue/{clean_key}/comment"
    payload = {
        "body": {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": comment_text}]
                }
            ]
        }
    }
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.post(url, auth=auth, headers={"Accept": "application/json", "Content-Type": "application/json"}, json=payload)
            if resp.status_code in [200, 201]:
                data = resp.json()
                comment_id = data.get("id")
                return f"Successfully added comment (ID: `{comment_id}`) to Jira ticket **{clean_key}**!"
            return f"Error adding comment (HTTP {resp.status_code}): {resp.text}"
    except Exception as e:
        return f"Error adding comment: {str(e)}"


@mcp.tool(
    name="jira_summarize_issue",
    description="Summarize full content and complete comment history of a Jira ticket (e.g. WAR-12)."
)
def jira_summarize_issue(issue_key: str) -> str:
    """Summarize full ticket content and complete comment history."""
    clean_key = issue_key.strip().upper()
    domain, auth = get_jira_auth_headers()
    url = f"https://{domain}/rest/api/3/issue/{clean_key}"
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(url, auth=auth, headers={"Accept": "application/json"})
            if resp.status_code == 200:
                data = resp.json()
                fields = data.get("fields", {})
                
                desc = extract_adf_text(fields.get("description")) or "No description provided."
                comments_list = fields.get("comment", {}).get("comments", [])
                
                formatted_comments = []
                for c in comments_list:
                    author = c.get("author", {}).get("displayName", "Unknown") if c.get("author") else "Unknown"
                    body_text = extract_adf_text(c.get("body"))
                    formatted_comments.append(f"- **{author}**: {body_text}")
                
                comments_summary = "\n".join(formatted_comments) if formatted_comments else "No comments on this ticket."
                
                return (
                    f"### Executive Summary for {clean_key}\n"
                    f"* **Title**: {fields.get('summary')}\n"
                    f"* **Status**: `{fields.get('status', {}).get('name')}`\n"
                    f"* **Assignee**: {fields.get('assignee', {}).get('displayName', 'Unassigned') if fields.get('assignee') else 'Unassigned'}\n\n"
                    f"#### 📄 Description\n{desc}\n\n"
                    f"#### 💬 Comment History Thread ({len(comments_list)} comments)\n{comments_summary}"
                )
            return f"Error fetching ticket summary (HTTP {resp.status_code}): {resp.text}"
    except Exception as e:
        return f"Error summarizing ticket: {str(e)}"


if __name__ == "__main__":
    port = int(os.getenv("PORT", 8080))
    logger.info(f"Starting Live FastMCP Server on port {port}...")
    mcp.run()



